### ISSUE TITLE
[Feature Request] Update Helm Chart to support Nacos 3.0.1 with MCP Registry API

### ISSUE THREAD

**Issue by buihutrungkinh** [ygqygq2/nacos-helm#31]
Dear @ygqygq2 
## Description

Please update the official Helm Chart to support Nacos version **3.0.1 (Released May 22, 2025)**.

This version introduces important features including:
- Multi-namespace and multi-version management for MCP Server.
- Standard MCP Registry API (`nacos.ai.mcp.registry.enabled=true`, `port=9080`).
- Stability improvements and important bug fixes.

## Requested Changes

- Upgrade Nacos image tag to `3.0.1`.
- Add ability to enable MCP Registry API via values:
  ```yaml
  mcp:
    enabled: true
    port: 9080
Add appropriate container port and environment variables when MCP is enabled:
- name: NACOS_AI_MCP_REGISTRY_ENABLED
  value: "true"
- name: NACOS_AI_MCP_REGISTRY_PORT
  value: "9080"
Expose additional port in the deployment/statefulset and service when MCP is enabled.
Reference
Release note: https://github.com/alibaba/nacos/releases/tag/3.0.1

Migration tool for MCP changes: mcp-migration-tool.jar
Why This is Important
This version includes breaking changes for MCP Registry compatibility. The chart should support enabling MCP Registry cleanly via Helm so that users can benefit from the new MCP features without manual edits.

Thanks in advance for the update!

**Comment by buihutrungkinh** [comment]
Hi @ygqygq2  , I’ve reviewed the [Nacos 3.0.1 release notes](https://github.com/nacos-group/nacos-docker) and would like to request an update to the Helm chart to support this version properly.

This version is based on 3.0.0 and introduces significant changes related to MCP (Multi-Cluster Platform):

Adds support for MCP's multi-namespace and multi-version management capabilities.

Introduces the standard MCP Registry API via the parameters:

nacos.ai.mcp.registry.enabled=true
nacos.ai.mcp.registry.port=9080

MCP support requires additional ports and should be configurable via Helm values.

However, there is a critical compatibility notice:

Due to changes in metadata definitions, upgrading from 3.0.0 to 3.0.1 may cause the console to fail reading data from previous MCP servers.

To address this, Nacos provides a migration tool: mcp-migration-tool.jar, which must be executed before using Nacos 3.0.1 in environments previously running 3.0.0.

📌 Suggestion
I recommend updating the Helm chart to 2.1.9:

Allow configuration of nacos.ai.mcp.registry.enabled and nacos.ai.mcp.registry.port through values.yaml.

Include guidance (or optionally, a Kubernetes Job) for running the mcp-migration-tool.jar during upgrades from 3.0.0.

Update the default image tag to 3.0.1 or allow users to opt in safely.

Let me know if I can help test the updated chart. Thanks for your support!

**Comment by ygqygq2** [comment]
[application.properties](https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties)

It does not come with the following configuration, so you need to map the configuration file yourself.

```
nacos.ai.mcp.registry.enabled=true
nacos.ai.mcp.registry.port=9080
```


```
## Enable configmap and add data in configmap
config:
  enabled: true
  mountPath: /home/nacos/conf/application.properties
  subPath: "application.properties"
  readOnly: true
  data:
    application.properties: |
      nacos.ai.mcp.registry.enabled=true
      nacos.ai.mcp.registry.port=9080
      #*************** Nacos port Related Configurations ***************#
      ### Nacos Server Main port
      nacos.server.main.port=${NACOS_APPLICATION_PORT:8848}
      
      #*************** Network Related Configurations ***************#
      ### If prefer hostname over ip for Nacos server addresses in cluster.conf:
      # nacos.inetutils.prefer-hostname-over-ip=false
      
      ### Specify local server's IP:
      # nacos.inetutils.ip-address=
      
      #*************** Datasource Related Configurations ***************#
      ### nacos.plugin.datasource.log.enabled=true
      spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:}
      ### Count of DB:
      # db.num=1
      
      ### Connect URL of DB:
      db.num=${MYSQL_DATABASE_NUM:1}
      db.url.0=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM:characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false}
      db.user.0=${MYSQL_SERVICE_USER}
      db.password.0=${MYSQL_SERVICE_PASSWORD}
      
      db.pool.config.connectionTimeout=${DB_POOL_CONNECTION_TIMEOUT:30000}
      db.pool.config.validationTimeout=10000
      db.pool.config.maximumPoolSize=20
      db.pool.config.minimumIdle=2
      
      #*************** Metrics Related Configurations ***************#
      ### Metrics for prometheus
      management.endpoints.web.exposure.include=prometheus
      
      ### Metrics for elastic search
      management.metrics.export.elastic.enabled=false
      #management.metrics.export.elastic.host=http://localhost:9200
      
      ### Metrics for influx
      management.metrics.export.influx.enabled=false
      #management.metrics.export.influx.db=springboot
      #management.metrics.export.influx.uri=http://localhost:8086
      #management.metrics.export.influx.auto-create-db=true
      #management.metrics.export.influx.consistency=one
      #management.metrics.export.influx.compressed=true
      
      #*************** Core Related Configurations ***************#
      
      ### set the WorkerID manually
      # nacos.core.snowflake.worker-id=
      
      ### Member-MetaData
      # nacos.core.member.meta.site=
      # nacos.core.member.meta.adweight=
      # nacos.core.member.meta.weight=
      
      ### MemberLookup
      ### Addressing pattern category, If set, the priority is highest
      # nacos.core.member.lookup.type=[file,address-server]
      
      ## Set the cluster list with a configuration file or command-line argument
      # nacos.member.list=192.168.16.101:8847?raft_port=8807,192.168.16.101?raft_port=8808,192.168.16.101:8849?raft_port=8809
      
      ## for AddressServerMemberLookup
      # Maximum number of retries to query the address server upon initialization
      # nacos.core.address-server.retry=5
      ## Server domain name address of [address-server] mode
      # address.server.domain=jmenv.tbsite.net
      ## Server port of [address-server] mode
      # address.server.port=8080
      ## Request address of [address-server] mode
      # address.server.url=/nacos/serverlist
      
      #*************** JRaft Related Configurations ***************#
      
      ### Sets the Raft cluster election timeout, default value is 5 second
      # nacos.core.protocol.raft.data.election_timeout_ms=5000
      ### Sets the amount of time the Raft snapshot will execute periodically, default is 30 minute
      # nacos.core.protocol.raft.data.snapshot_interval_secs=30
      ### raft internal worker threads
      # nacos.core.protocol.raft.data.core_thread_num=8
      ### Number of threads required for raft business request processing
      # nacos.core.protocol.raft.data.cli_service_thread_num=4
      ### raft linear read strategy. Safe linear reads are used by default, that is, the Leader tenure is confirmed by heartbeat
      # nacos.core.protocol.raft.data.read_index_type=ReadOnlySafe
      ### rpc request timeout, default 5 seconds
      # nacos.core.protocol.raft.data.rpc_request_timeout_ms=5000
      ### enable to support prometheus service discovery
      #nacos.prometheus.metrics.enabled=true
      
      #*************** Distro Related Configurations ***************#
      
      ### Distro data sync delay time, when sync task delayed, task will be merged for same data key. Default 1 second.
      # nacos.core.protocol.distro.data.sync.delayMs=1000
      ### Distro data sync timeout for one sync data, default 3 seconds.
      # nacos.core.protocol.distro.data.sync.timeoutMs=3000
      ### Distro data sync retry delay time when sync data failed or timeout, same behavior with delayMs, default 3 seconds.
      # nacos.core.protocol.distro.data.sync.retryDelayMs=3000
      ### Distro data verify interval time, verify synced data whether expired for a interval. Default 5 seconds.
      # nacos.core.protocol.distro.data.verify.intervalMs=5000
      ### Distro data verify timeout for one verify, default 3 seconds.
      # nacos.core.protocol.distro.data.verify.timeoutMs=3000
      ### Distro data load retry delay when load snapshot data failed, default 30 seconds.
      # nacos.core.protocol.distro.data.load.retryDelayMs=30000
      ### enable to support prometheus service discovery
      #nacos.prometheus.metrics.enabled=true
      
      #*************** Grpc Configurations ***************#
      
      ### Sets the maximum message size allowed to be received on the server.
      #nacos.remote.server.grpc.sdk.max-inbound-message-size=10485760
      ### Sets the time(milliseconds) without read activity before sending a keepalive ping. The typical default is two hours.
      #nacos.remote.server.grpc.sdk.keep-alive-time=7200000
      ### Sets a time(milliseconds) waiting for read activity after sending a keepalive ping. Defaults to 20 seconds.
      #nacos.remote.server.grpc.sdk.keep-alive-timeout=20000
      ### Sets a time(milliseconds) that specify the most aggressive keep-alive time clients are permitted to configure. The typical default is 5 minutes
      #nacos.remote.server.grpc.sdk.permit-keep-alive-time=300000
      ### cluster grpc(inside the nacos server) configuration
      #nacos.remote.server.grpc.cluster.max-inbound-message-size=10485760
      ### Sets the time(milliseconds) without read activity before sending a keepalive ping. The typical default is two hours.
      #nacos.remote.server.grpc.cluster.keep-alive-time=7200000
      ### Sets a time(milliseconds) waiting for read activity after sending a keepalive ping. Defaults to 20 seconds.
      #nacos.remote.server.grpc.cluster.keep-alive-timeout=20000
      ### Sets a time(milliseconds) that specify the most aggressive keep-alive time clients are permitted to configure. The typical default is 5 minutes
      #nacos.remote.server.grpc.cluster.permit-keep-alive-time=300000
      
      #*************** Config Module Related Configurations ***************#
      
      ### the maximum retry times for push
      nacos.config.push.maxRetryTime=50
      
      #*************** Naming Module Related Configurations ***************#
      ### Data dispatch task execution period in milliseconds:
      
      ### If enable data warmup. If set to false, the server would accept request without local data preparation:
      nacos.naming.data.warmup=true
      
      ### If enable the instance auto expiration, kind like of health check of instance:
      # nacos.naming.expireInstance=true
      
      nacos.naming.empty-service.auto-clean=true
      nacos.naming.empty-service.clean.initial-delay-ms=50000
      nacos.naming.empty-service.clean.period-time-ms=30000
      
      #--------------- Nacos Web Server Configurations ---------------#
      
      #*************** Nacos Web Server Related Configurations ***************#
      ### Nacos Server Web context path:
      nacos.server.contextPath=${SERVER_SERVLET_CONTEXTPATH:/nacos}
      
      #*************** Access Log Related Configurations ***************#
      ### If turn on the access log:
      server.tomcat.accesslog.enabled=true
      
      ### accesslog automatic cleaning time
      server.tomcat.accesslog.max-days=30
      
      ### The access log pattern:
      server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
      
      ### The directory of access log:
      server.tomcat.basedir=file:.
      
      #*************** API Related Configurations ***************#
      ### Include message field
      server.error.include-message=ALWAYS
      
      ### Enabled for open API compatibility
      # nacos.core.api.compatibility.client.enabled=true
      ### Enabled for admin API compatibility
      # nacos.core.api.compatibility.admin.enabled=false
      ### Enabled for console API compatibility
      # nacos.core.api.compatibility.console.enabled=false
      
      #--------------- Nacos Console Configurations ---------------#
      
      #*************** Nacos Console Related Configurations ***************#
      ### Nacos Console Main port
      nacos.console.port=${NACOS_CONSOLE_PORT:8080}
      ### Nacos Server Web context path:
      nacos.console.contextPath=${NACOS_CONSOLE_CONTEXTPATH:}
      
      ### Nacos Server context path, which link to nacos server `nacos.server.contextPath`, works when deployment type is `console`
      nacos.console.remote.server.context-path=${SERVER_SERVLET_CONTEXTPATH:/nacos}
      
      #************** Console UI Configuration ***************#
      
      ### Turn on/off the nacos console ui.
      nacos.console.ui.enabled=true
      
      #--------------- Nacos Plugin Configurations ---------------#
      
      #*************** CMDB Plugin Related Configurations ***************#
      ### The interval to dump external CMDB in seconds:
      # nacos.cmdb.dumpTaskInterval=3600
      
      ### The interval of polling data change event in seconds:
      # nacos.cmdb.eventTaskInterval=10
      
      ### The interval of loading labels in seconds:
      # nacos.cmdb.labelTaskInterval=300
      
      ### If turn on data loading task:
      # nacos.cmdb.loadDataAtStart=false
      
      #*************** Auth Plugin Related Configurations ***************#
      ### The ignore urls of auth, will be deprecated in the future:
      nacos.security.ignore.urls=${NACOS_SECURITY_IGNORE_URLS:/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**}
      
      ### The auth system to use, default 'nacos' and 'ldap' is supported, other type should be implemented by yourself:
      nacos.core.auth.system.type=${NACOS_AUTH_SYSTEM_TYPE:nacos}
      
      ### If turn on auth system:
      # Whether open nacos server API auth system
      nacos.core.auth.enabled=false
      # Whether open nacos admin API auth system
      nacos.core.auth.admin.enabled=true
      # Whether open nacos console API auth system
      nacos.core.auth.console.enabled=true
      
      ### Turn on/off caching of auth information. By turning on this switch, the update of auth information would have a 15 seconds delay.
      nacos.core.auth.caching.enabled=${NACOS_AUTH_CACHE_ENABLE:false}
      
      ### worked when nacos.core.auth.enabled=true
      ### The two properties is the white list for auth and used by identity the request from other server.
      nacos.core.auth.server.identity.key=${NACOS_AUTH_IDENTITY_KEY:}
      nacos.core.auth.server.identity.value=${NACOS_AUTH_IDENTITY_VALUE:}
      
      ### worked when nacos.core.auth.system.type=nacos or nacos.core.auth.console.enabled=true
      ### The token expiration in seconds:
      nacos.core.auth.plugin.nacos.token.cache.enable=false
      nacos.core.auth.plugin.nacos.token.expire.seconds=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS:18000}
      ### The default token (Base64 string):
      #nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_AUTH_TOKEN:}
      
      ### worked when nacos.core.auth.system.type=ldap?{0} is Placeholder,replace login username
      #nacos.core.auth.ldap.url=ldap://localhost:389
      #nacos.core.auth.ldap.basedc=dc=example,dc=org
      #nacos.core.auth.ldap.userDn=cn=admin,${nacos.core.auth.ldap.basedc}
      #nacos.core.auth.ldap.password=admin
      #nacos.core.auth.ldap.userdn=cn={0},dc=example,dc=org
      #nacos.core.auth.ldap.filter.prefix=uid
      #nacos.core.auth.ldap.case.sensitive=true
      #nacos.core.auth.ldap.ignore.partial.result.exception=false
      
      #*************** Control Plugin Related Configurations ***************#
      # plugin type
      #nacos.plugin.control.manager.type=nacos
      
      # local control rule storage dir, default ${nacos.home}/data/connection and ${nacos.home}/data/tps
      #nacos.plugin.control.rule.local.basedir=${nacos.home}
      
      # external control rule storage type, if exist
      #nacos.plugin.control.rule.external.storage=
      
      #*************** Config Change Plugin Related Configurations ***************#
      # webhook
      #nacos.core.config.plugin.webhook.enabled=false
      # It is recommended to use EB https://help.aliyun.com/document_detail/413974.html
      #nacos.core.config.plugin.webhook.url=http://localhost:8080/webhook/send?token=***
      # The content push max capacity ,byte
      #nacos.core.config.plugin.webhook.contentMaxCapacity=102400
      
      # whitelist
      #nacos.core.config.plugin.whitelist.enabled=false
      # The import file suffixs
      #nacos.core.config.plugin.whitelist.suffixs=xml,text,properties,yaml,html
      # fileformatcheck,which validate the import file of type and content
      #nacos.core.config.plugin.fileformatcheck.enabled=false
      
      #*************** Istio Plugin Related Configurations ***************#
      ### If turn on the MCP server:
      nacos.istio.mcp.server.enabled=false
      
      #--------------- Nacos Experimental Features Configurations ---------------#
      
      #*************** K8s Related Configurations ***************#
      ### If turn on the K8s sync:
      nacos.k8s.sync.enabled=false
      
      ### If use the Java API from an application outside a kubernetes cluster
      #nacos.k8s.sync.outsideCluster=false
      #nacos.k8s.sync.kubeConfig=/.kube/config
      
      #*************** Deployment Type Configuration ***************#
      
      ### Sets the deployment type: 'merged' for joint deployment, 'server' for separate deployment server only, 'console' for separate deployment console only.
      nacos.deployment.type=merged
```
