### ISSUE TITLE
开启Prometheus Exporter / Metrics功能，不能正常启动

### ISSUE THREAD

**Issue by royalwang** [ygqygq2/nacos-helm#8]
```yaml
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/nginx-exporter
    tag: 0.10.0
```

Could not create Nginx Client: Failed to create NginxClient: failed to get http://127.0.0.1:8080/stub_status: Get http://127.0.0.1:8080/stub_status: dial tcp 127.0.0.1:8080: connect: connection refused.
